Init feature
ShinobiWarior/bookstore pull request #1
Opened 2021-09-27 18:54 UTC by ShinobiWarior

Changes:
 - Initialised React app
 - Added React Redux
 - Structured application files using the ducks pattern for  Redux files
 - Added React Router and set two Route-s and Link-s for the app's navigation:
    - Books
       -  Default view - will display the list of books and add/remove book functionality.
   -  Categories
       -  Should display "Under construction" text only.

2021-09-27 20:06 UTC, Dipeshtwis requested changes
Hi @ShinobiWarior, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: The project structure is nice.
:+1: I really appreciate you for your extra work, but there was no need to add the adding/removing book functionality in this milestone, it will ask in the next one. So always try to implement the thing as per project need. 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

**_Check the comments under the review_**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-27 20:06 UTC, Dipeshtwis commented on src/components/Books.js
> +        </button>
- [x] Instead of directly rendering the form, I would recommend making a separate component for creating a new book. So, that if you want to reuse that component, it will be easily available.

2021-09-28 09:06 UTC, henatan99 commented on src/components/Books.js
> +        </button>
This issue is well addressed. Great work! :clap:

2021-09-28 09:11 UTC, henatan99 approved these changes
Hi @ShinobiWarior , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- [ ] OPTIONAL: There is an important issue not mentioned by the previous reviewer. You did not follow the correct GitHub flow for this project. You should have a development branch that should be set as the default branch and on top of that, you will have a feature branch. So your PR should be from the feature branch to the development branch. Kindly take this seriously and make sure you follow the correct GitHub flow in your next milestones. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-28 09:52 UTC, merged